---
name: BottledEXP
main: BottledEXp/Main
author: skullex
api: [2.0.0]

commands:
  exp:
    description: Main Bottled EXP command
    usage: /exp bottle
    aliases: [e]
    permission: bottle.exp
  
permissions:
  bottle.exp:
    default: op
    description: Bottle your EXP
...
